Check if token is provided
discordeno/discordeno pull request #1029
Opened 2021-06-10 11:39 UTC by lumap

better error handling - a "no token" error is better than 

Error: [401] The Authorization header was missing or invalid.
    at Object.processQueue (https://deno.land/x/discordeno@11.0.3/src/rest/process_queue.ts:101:40)
    at async Object.processRequest (https://deno.land/x/discordeno@11.0.3/src/rest/process_request.ts:31:5)

2021-06-10 11:41 UTC, itohatweb requested changes

2021-06-10 11:41 UTC, itohatweb commented on src/bot.ts
> +  if (!config.token) throw Error("No token provided!")
Good Idea but please add the error to our Errors enum and don't forget the new keyword so like
`throw new Error(Errors.NO_TOKEN_PROVIDED)`

2021-06-10 11:53 UTC, itohatweb commented
oh wait shouldn't ts prevent this?

2021-06-10 12:00 UTC, lumap commented
> oh wait shouldn't ts prevent this?

What do you mean?

2021-06-10 12:03 UTC, itohatweb commented
Typescript gives you a visual error if you do not provide a token
![image](https://user-images.githubusercontent.com/72305210/121521582-2844e280-c9ec-11eb-9c41-7153ce373e6b.png)

2021-06-10 12:04 UTC, lumap commented
if you provide an empty string typescript says it's okay tho

2021-06-10 13:20 UTC, closed without merging

2021-06-16 16:37 UTC, abhiss commented
> I don't agree with this PR. If you give a bad token, that's really on the developer themself. TS will already check and warn the user. Even if they don't it will error in a second and you can see the token is invalid

The current error doesn't tell you the token is invalid, it it reads `Error: [401] The Authorization header was missing or invalid`, followed by a stack trace. A lot of new developers make discord bots and messing up the token is a reasonable mistake for a beginner to make. I think it would help new users if the error mentioned the API token.

2021-06-16 16:40 UTC, itohatweb commented
`The Authorization header was missing or invalid` is just a nicer error message from our side which can easily be changed. Maybe we find a better name and then change it in our code would this be ok for you?

2021-06-16 17:20 UTC, abhiss commented
@itohatweb I think that would be great :)