fix(helpers): pass null if options.channelId is falsy
discordeno/discordeno pull request #1092
Opened 2021-08-09 19:25 UTC by rigormorrtiss

![image](https://user-images.githubusercontent.com/83530936/128762556-2114231a-4324-4797-8f4a-3fe06a6777f1.png)

2021-08-09 19:33 UTC, itohatweb requested changes
This is a bad solution. With that one you require the user to always pass a channelId if the bot shall not move the user.

2021-08-10 00:39 UTC, Skillz4Killz commented
We have `disconnectMember()` no?

2021-08-10 07:26 UTC, golfIII commented
> 
> 
> We have `disconnectMember()` no?

Hi, I'm the Discord member in the image above.

Same issue occurs when using `disconnectMember()`. Perms are valid, channel is valid, and the member being kicked is valid and is successfully returned from both `channel.disconnect()` and `disconnectMember()`.

I believe @ayntee was able to reproduce the issue on his end as well.

2021-08-10 10:10 UTC, ayntee commented
@Skillz4Killz disconnectMember() calls editMember() under the hood

2021-08-10 10:10 UTC, ayntee commented
> This is a bad solution. With that one you require the user to always pass a channelId if the bot shall not move the user.

@itohatweb looks like the PR has been updated

2021-08-11 16:23 UTC, Skillz4Killz commented on src/helpers/members/edit_member.ts
> +      channelId: typeof options.channelId === "bigint" ? bigintToSnowflake(options.channelId) : options.channelId,
```suggestion
      channelId: options.channelId ? bigintToSnowflake(options.channelId) : options.channelId,
```

2021-08-11 16:24 UTC, Skillz4Killz approved these changes

2021-08-11 16:24 UTC, merged