make some function params optional
discordeno/discordeno pull request #1846
Opened 2021-12-14 15:12 UTC by some-boi

if all the properties in it is optional then why is it required

2021-12-14 15:14 UTC, itohatweb commented
What's the reasoning of making them optional?

2021-12-14 15:16 UTC, some-boi commented
> What's the reasoning of making them optional?

~~annoying~~
ya ive been checking the code  and realized it so i decided to fix that stuff even tho it does nothing so idk

2021-12-14 15:23 UTC, itohatweb commented
> > What's the reasoning of making them optional?
> 
> ~annoying~ ya ive been checking the code and realized it so i decided to fix that stuff even tho it does nothing so idk

I understand now. 
Please make this a breaking change hehe. Move the guild icon hash stuff out of the options and make it an undefinable param (`icon?: string | bigint`). 
For avatar urls there can be discussed whats the better method.
Please revert the changes from `editBotProfile` and open an issue indicating that the user should provide at least one option of it. (PS: if you want to figure the types out you can do this of course.)

2021-12-15 14:34 UTC, lts20050703 requested changes
<https://deno.land/manual@v1.16.4/contributing/style_guide#exported-functions-max-2-args-put-the-rest-into-an-options-object>
avatarUrl.ts ✅
guildIconUrl.ts and guildSplashUrl.ts: As much as it annoys you, it annoys more people having to deal with this breaking change and 4 parameters is too much.

2021-12-15 14:38 UTC, itohatweb commented
4 options are ok for us. It should not be more than 4 though. V13 is already a big change this won't change much. Also not many ppl use it I would say.
imho

2021-12-16 04:38 UTC, lts20050703 commented
@some-boi If you have a discord account consider joining https://discord.gg/RxaygRBt
![image](https://user-images.githubusercontent.com/87189679/146309005-3dc693aa-8653-47bd-b0b0-d5ca7aa7795d.png)

2021-12-16 07:00 UTC, itohatweb commented
What is this Discord Server invite link 🤔
It's not discordeno

2021-12-16 10:12 UTC, Yaikava commented
> What is this Discord Server invite link 🤔 It's not discordeno

It is discordeno.

2021-12-16 10:54 UTC, itohatweb commented
Lol for me it looked like a vanity invite 🤣

2021-12-16 15:26 UTC, some-boi commented
> 



> @some-boi If you have a discord account consider joining https://discord.gg/RxaygRBt ![image](https://user-images.githubusercontent.com/87189679/146309005-3dc693aa-8653-47bd-b0b0-d5ca7aa7795d.png)

but im there (a boi here ;o#6969 or by nick Major General Henry Landry)

2021-12-17 13:26 UTC, lts20050703 commented
> > 
> 
> > @some-boi If you have a discord account consider joining https://discord.gg/RxaygRBt ![image](https://user-images.githubusercontent.com/87189679/146309005-3dc693aa-8653-47bd-b0b0-d5ca7aa7795d.png)
> 
> but im there (a boi here ;o#6969 or by nick Major General Henry Landry)

oh... oops sorry I dont know your discord username and you're already in there lol

2021-12-19 17:11 UTC, Skillz4Killz requested changes

2021-12-19 17:11 UTC, Skillz4Killz commented on src/helpers/guilds/guildIconUrl.ts
> +  icon: string | bigint | undefined,
@itohatweb

2021-12-20 00:38 UTC, lts20050703 commented on src/helpers/guilds/guildIconUrl.ts
> +  icon: string | bigint | undefined,
imo if we're gonna make v13 ~~"the nuke update"~~ "the functional and bigint update" then imo we should break backward compatibility

2021-12-20 17:49 UTC, some-boi commented on src/helpers/guilds/guildIconUrl.ts
> +  icon: string | bigint | undefined,
i also dont see a point on it since the types are know bigint | undefined

2021-12-21 00:42 UTC, Skillz4Killz approved these changes

2021-12-21 00:42 UTC, Skillz4Killz commented
Great PR!

2021-12-21 00:43 UTC, merged