Clarification on channel icons
discordeno/discordeno pull request #1925
Opened 2022-01-26 03:26 UTC by lts20050703

Closes: #1904

2022-01-26 05:29 UTC, Skillz4Killz requested changes
Bots cant be in group dms id prefer we remove this instead

2022-01-26 13:50 UTC, Skillz4Killz approved these changes
Does this need removing in a helper/transformer?

2022-01-27 03:31 UTC, lts20050703 commented
> Does this need removing in a helper/transformer?

Helpers like getChannel use channel transformer so yeah we only need to fix the channel transformer

2022-01-27 16:29 UTC, Skillz4Killz approved these changes

2022-01-28 08:57 UTC, closed without merging