Move the shard stopping to gatewayManager in order to stop the gateway standalone.
discordeno/discordeno pull request #2078
Opened 2022-02-26 16:39 UTC by AFink

2022-02-26 16:50 UTC, itohatweb requested changes
Looks good overall, just a few nit-picks.

2022-02-26 16:50 UTC, itohatweb commented on gateway/gateway_manager.ts
> +  /** Use this function to stop the gateway properly */
```suggestion
  /** Use this function to stop the gateway properly. */
```

2022-02-26 16:50 UTC, itohatweb commented on gateway/stopGateway.ts
> +}
```suggestion
    await delay(5000);
}

```

2022-02-26 16:59 UTC, itohatweb submitted a review, later dismissed

2022-02-27 20:13 UTC, Skillz4Killz commented on gateway/stopGateway.ts
> +export async function stopGateway(gateway: GatewayManager) {
```suggestion
export async function stopGateway(gateway: GatewayManager, code = 3061, reason = "Discordeno Testing Finished! Do Not RESUME!") {

```

2022-02-27 20:13 UTC, Skillz4Killz commented on gateway/stopGateway.ts
> +          "Discordeno Testing Finished! Do Not RESUME!",
```suggestion
          reason,
```

2022-02-27 20:13 UTC, Skillz4Killz commented on gateway/stopGateway.ts
> +          3061,
```suggestion
          code,

```

2022-02-28 18:40 UTC, Skillz4Killz approved these changes

2022-02-28 18:41 UTC, merged