🐛 fix: perms plugin - edit webhook
discordeno/discordeno pull request #2082
Opened 2022-03-09 09:11 UTC by Yaikava

2022-03-09 10:40 UTC, lts20050703 requested changes
`ModifyWebhook` already has `channelId`
https://github.com/discordeno/discordeno/blob/7e69f29217e463a4bc6b0d8fb4336d360ce24c42/types/webhooks/modifyWebhook.ts#L8
<img width="166" alt="image" src="https://user-images.githubusercontent.com/87189679/157425093-4459cfec-7062-4b08-b3bc-9963f2c7c293.png">

2022-03-09 10:40 UTC, lts20050703 commented on helpers/webhooks/editWebhook.ts
> +export async function editWebhook(bot: Bot, webhookId: bigint, options: ModifyWebhook, channelId?: bigint) {
```suggestion
export async function editWebhook(bot: Bot, webhookId: bigint, options: ModifyWebhook) {
```

2022-03-09 10:40 UTC, lts20050703 commented on plugins/permissions/src/webhooks/editWebhook.ts
> +  bot.helpers.editWebhook = async function (webhookId, options, channelId) {
```suggestion
  bot.helpers.editWebhook = async function (webhookId, options) {
```

2022-03-09 10:40 UTC, lts20050703 commented on plugins/permissions/src/webhooks/editWebhook.ts
> +    if (channelId) requireBotChannelPermissions(bot, channelId, ["MANAGE_WEBHOOKS"]);
```suggestion
    if (options.channelId) requireBotChannelPermissions(bot, options.channelId, ["MANAGE_WEBHOOKS"]);
```

2022-03-09 10:40 UTC, lts20050703 commented on plugins/permissions/src/webhooks/editWebhook.ts
> +    return await editWebhookOld(webhookId, options, channelId);
```suggestion
    return await editWebhookOld(webhookId, options);
```

2022-03-21 08:26 UTC, Skillz4Killz commented
Overriden directly. Thanks yui, implemented your idea with a few modifications

2022-03-21 08:26 UTC, closed without merging