2213 separate g UI ld create fields from guild object
discordeno/discordeno pull request #2224
Opened 2022-05-14 08:06 UTC by lts20050703

Closes: https://github.com/discordeno/discordeno/issues/2213
Upstream: https://github.com/discord/discord-api-docs/commit/78a152e

types: Add DiscordGuildCreate interface
transformers: Create GuildCreateToggles and transformGuildCreate transformer
handlers: handleGuildCreate use the transformGuildCreate transformer

2022-05-14 10:57 UTC, itohatweb requested changes
Please revert the unrelated format changes

2022-05-14 10:57 UTC, itohatweb commented on transformers/guildCreate.ts
> +  const guild = {
Please do `...transformGuild(payload)` and then just add the other fields

2022-05-14 10:57 UTC, itohatweb commented on transformers/toggles/guild.ts
> +  }
Move to separate file

2022-05-14 19:49 UTC, itohatweb approved these changes

2022-05-15 18:33 UTC, Skillz4Killz commented
Not a fan of this PR. I don't want to go this route where we end up having like 20 different transformers for a channel because each has a few different props on it.

2022-05-16 07:23 UTC, itohatweb commented
We won't do that for channels, since TypeScript does not provide anything what we could use and still maintain a good UX.
But it is different in this case. Why not say through types that eg. `channels` never exists when you use the `getGuild` helper.

2022-05-16 12:45 UTC, Skillz4Killz commented
That can be done with types without having to create multiple transformers for each type.

```ts
function getGuild() {
  return {} as SpecialGuildInterface;
}
```

2022-05-16 12:45 UTC, closed without merging