Slash command perms v2
discordeno/discordeno pull request #2226
Opened 2022-05-15 07:33 UTC by lts20050703

Closes: #2184
Upstream: discord/discord-api-docs@4a3b20a

- Nuke batchEditApplicationCommandPermissions (https://discord.com/developers/docs/interactions/application-commands#batch-edit-application-command-permissions)
- update JSDocs Comments (like, a lot, probably will revert unnecessary comments changes next commit)
- Add id to upsertApplicationCommands options
# Please review carefully! It's not like I'm not responsible but the v2 update is huge and it's very likely I missed something!

2022-05-15 07:51 UTC, meister03 reviewed
Interesting changes, will compare them with the documentation tonight. Everything else looks fine

2022-05-15 10:00 UTC, itohatweb requested changes

2022-05-15 10:03 UTC, lts20050703 commented on types/discord.ts
> +  /**	Name of command, 1-32 characters */
I think it's unnecessary but I will revert that

2022-05-24 20:34 UTC, itohatweb commented
Can you rebase this PR to #2238?

2022-05-25 16:38 UTC, lts20050703 commented
> Can you rebase this PR to #2238?

@itohatweb resolved merge conflicts

2022-05-25 20:30 UTC, itohatweb commented
I'M too lazy to review

2022-05-25 20:32 UTC, itohatweb approved these changes
lgtm for now

2022-05-25 20:32 UTC, merged