update: Update kwik to 1.3.0
discordeno/discordeno pull request #2424
Opened 2022-09-01 11:32 UTC by TriForMine

2022-09-01 15:45 UTC, lts20050703 approved these changes

2022-09-01 15:49 UTC, lts20050703 commented
please run `deno fmt`

2022-09-01 17:35 UTC, Skillz4Killz commented
@TriForMine 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/23035000/187977376-3b228d07-6e19-4961-bf1a-883fd4bfef80.png">

2022-09-02 09:31 UTC, lts20050703 requested changes

2022-09-02 09:36 UTC, lts20050703 approved these changes

2022-09-02 16:11 UTC, Skillz4Killz approved these changes

2022-09-02 16:11 UTC, merged