Updated example code to match final version
discordeno/discordeno pull request #2426
Opened 2022-09-02 12:05 UTC by raluvy95

- Changed the dependency import to match final version
- Turn the type value of `Deno.env.get("BOT_ID")` into bigint (I am unsure if this is necessary)

2022-09-02 16:11 UTC, Skillz4Killz commented on README.md
> +  botId: BigInt(Deno.env.get("BOT_ID") || 0),
This entire line can be removed, it is no longer necessary

2022-09-02 16:43 UTC, lts20050703 requested changes

2022-09-02 16:43 UTC, lts20050703 commented on README.md
> +  botId: BigInt(Deno.env.get("BOT_ID") || 0),
```suggestion
```

2022-09-03 16:41 UTC, Skillz4Killz approved these changes

2022-09-03 16:41 UTC, merged