fix: Export of `ApplicationCommandOptionChoice`.
discordeno/discordeno pull request #2448
Opened 2022-09-09 16:13 UTC by vxern

2022-09-09 19:59 UTC, itohatweb approved these changes

2022-09-09 22:46 UTC, lts20050703 approved these changes
Export of ApplicationCommandOptionChoice is already done in https://github.com/discordeno/discordeno/pull/2446/files#diff-b866dc3f646e1bd66564228107e0a2ea9840026bc67b87b53cbaa35ce5a6b810 btw

https://discord.com/developers/docs/interactions/application-commands#bulk-overwrite-global-application-commands

https://discord.com/developers/docs/interactions/application-commands#bulk-overwrite-guild-application-commands

LGTM nonetheless!

2022-09-09 22:49 UTC, lts20050703 requested changes
please run `deno fmt`

2022-09-09 23:03 UTC, lts20050703 commented
@vxern deno fmt should output something like this
```
PS C:\git\dd> deno fmt    
C:\git\dd\plugins\cache\src\dispatchRequirements.ts
C:\git\dd\template\bigbot\src\bot\utils\slash\updateCommands.ts
C:\git\dd\transformers\invite.ts
C:\git\dd\template\bigbot\src\bot\utils\slash\createCommand.ts
C:\git\dd\template\bigbot\src\bot\events\raw.ts
C:\git\dd\packages\embeds\mod.ts
Checked 692 files
```
If you only see the "checked 692 files" line, you will need to run `deno upgrade`
Deno fmt latest version change some stuff

2022-09-10 00:43 UTC, Skillz4Killz approved these changes

2022-09-10 00:43 UTC, merged