fix(transformers): add min and max length to text input components
discordeno/discordeno pull request #2492
Opened 2022-09-29 20:45 UTC by ySnoopyDogy

The component transformer and the reverse transformer don't parse the min and max length of a text input component.
This PR fixed this problem.

2022-09-29 22:09 UTC, lts20050703 requested changes
please add the following
```ts
minLength: option.min_length
maxLength: option.max_length
```
to the return object in transformers/component.ts
**and run `deno fmt`**

2022-09-29 22:12 UTC, lts20050703 commented
@ySnoopyDogy just run `deno fmt`, you dont have to manually fix formatting

2022-09-29 22:14 UTC, ySnoopyDogy commented
ops, I never used deno before lol

2022-09-29 22:15 UTC, lts20050703 commented
Oh really? It's okay, have you installed deno? if not, here's the instructions https://deno.land/#installation

2022-09-29 23:14 UTC, lts20050703 approved these changes
LGMT (Looks Good To Me!)

2022-09-30 13:28 UTC, Skillz4Killz approved these changes

2022-09-30 13:28 UTC, merged