chore: remove client pkg
discordeno/discordeno pull request #2903
Opened 2023-03-29 16:03 UTC by Skillz4Killz

2023-03-29 16:15 UTC, itohatweb submitted a review, later dismissed

2023-03-29 17:19 UTC, itohatweb submitted a review, later dismissed

2023-03-29 17:36 UTC, H01001000 approved these changes

2023-03-29 17:37 UTC, H01001000 requested changes
need run yarn install

2023-03-30 07:15 UTC, H01001000 approved these changes

2023-03-30 07:26 UTC, itohatweb approved these changes

2023-03-30 07:32 UTC, TriForMine approved these changes

2023-03-30 14:48 UTC, merged