feat: commandOptionsParser util
discordeno/discordeno pull request #2961
Opened 2023-04-03 16:59 UTC by Skillz4Killz

2023-04-03 17:06 UTC, Skillz4Killz commented
@H01001000 Hey can you look at the issue here in deno unit test plz

2023-04-03 17:32 UTC, H01001000 requested changes

2023-04-03 17:32 UTC, H01001000 commented on packages/utils/tests/interactions.spec.ts
> +import { describe } from 'mocha'
```suggestion
import { describe, it } from 'mocha'
```

2023-04-03 17:36 UTC, H01001000 submitted a review, later dismissed

2023-04-03 17:54 UTC, itohatweb requested changes

2023-04-03 17:54 UTC, itohatweb commented on packages/utils/src/interactions.ts
> +    switch (option.type) {
Please add support and tests for those types too:
```ts
Boolean,
Mentionable,
Number,
Attachment,
```

2023-04-04 11:45 UTC, Skillz4Killz commented
@itohatweb ready to merge

2023-04-04 11:47 UTC, itohatweb approved these changes

2023-04-04 11:48 UTC, merged