types: rewrite API types
discordeno/discordeno pull request #310
Opened 2020-12-31 11:05 UTC by ayntee

@itohatweb :heart:

2021-01-10 11:07 UTC, ayntee commented on src/api/controllers/cache.ts
> +export const cacheHandlers = {
`const` -> `let`

2021-01-10 11:07 UTC, ayntee commented on src/api/controllers/cache.ts
> +export const cacheHandlers = {
```suggestion
// deno-lint-ignore prefer-const
export let cacheHandlers = {
```

2021-01-10 11:09 UTC, ayntee commented on src/api/controllers/interactions.ts
> +  const member: GuildMemberPayload | undefined = camelKeysToSnakeCase(
@itohatweb can you remove this? No breaking changes.

2021-01-10 11:50 UTC, itohatweb commented on src/api/controllers/cache.ts
> +export const cacheHandlers = {
lgtm

2021-01-10 13:02 UTC, itohatweb commented
Found something that needs to be done. I'm already on that, please don't merge.

2021-01-14 08:18 UTC, itohatweb commented on src/api/controllers/interactions.ts
> +  if (!member) return;
Well thats needed. Any Idea to change?

2021-01-14 08:20 UTC, itohatweb commented on src/api/handlers/channel.ts
> +        : camelKeysToSnakeCase(content.reply),
What do you want here?

2021-01-14 08:23 UTC, itohatweb commented on src/api/controllers/messages.ts
> +        },
Typescript does not like if I don't put default values here. I try to search a better solution.

2021-01-14 09:56 UTC, itohatweb commented on src/api/handlers/channel.ts
> +        : camelKeysToSnakeCase(content.reply),
Actually I made this change to prevent breaking changes

2021-01-16 09:44 UTC, itohatweb requested changes

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/channel.ts
> +  });
Use the converter function

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/guild.ts
> -  reason?: string,
Add this back

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/guild.ts
> -  reason?: string,
Add this back

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/guild.ts
> +    { ...snakeKeysToCamelCase(options) },
Spreading is unnecessary

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/member.ts
> -  reason?: string,
Add this back

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/member.ts
> -  reason?: string,
Add this back

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/member.ts
> -export async function kick(guildID: string, memberID: string, reason?: string) {
Add this back

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/message.ts
> -  reason?: string,
Add this back

2021-01-16 09:44 UTC, itohatweb commented on src/api/handlers/webhook.ts
> +    { ...camelKeysToSnakeCase(options) },
Spreading is unnecessary

2021-01-16 09:44 UTC, itohatweb commented on src/api/structures/guild.ts
> +    return Boolean(this.features?.includes(GuildFeatures.VERIFIED));
We want strings back

2021-01-16 09:44 UTC, itohatweb commented on src/rest/request_manager.ts
> +    console.error(Deno.inspect(error, { depth: 10 }));
remove this

2021-01-24 20:11 UTC, itohatweb commented
TODO: fix interaction module

2021-02-20 08:49 UTC, closed without merging