feat: made some progress on a function which can be overridden to all…
discordeno/discordeno pull request #3122
Opened 2023-09-18 05:07 UTC by 8auu

…ow users to inject custom headers into a rest request

2023-09-18 07:27 UTC, itohatweb commented
Hey, just a quick question, is there a reason for it being a function?

2023-09-18 10:55 UTC, 8auu commented
> Hey, just a quick question, is there a reason for it being a function?

A function would allow a developer to use dynamic values that need to be changed on each request, a property inside of the createRestManager class would not, unless you were overriding it every time you wanted a value to change which could be a little tedious.

A dynamic date header which changes based on when the request was made - Although, now I think about this example its not entirely useful unless you want to know how long a request takes to resolve and log it. As you could just create a new Date on the rests server instead.

I cannot come up with any other ideas, but I'm sure someone would have something down the line. Adds a bit more flexibility to what can be customized.

2023-09-19 15:11 UTC, Skillz4Killz requested changes

2023-09-19 20:14 UTC, Skillz4Killz approved these changes

2023-09-19 20:14 UTC, merged