refactor: ignore handlers if events for an handler isnt provided
discordeno/discordeno pull request #3148
Opened 2023-10-08 16:35 UTC by AwesomeStickz

2023-10-09 01:32 UTC, Skillz4Killz requested changes

2023-10-09 01:32 UTC, Skillz4Killz commented on packages/bot/src/handlers/channels/CHANNEL_CREATE.ts
> +  if (bot.events.channelCreate === undefined) return
eww

2023-10-09 01:32 UTC, Skillz4Killz commented on packages/bot/src/handlers/channels/CHANNEL_DELETE.ts
> +  if (bot.events.channelDelete === undefined) return
eww

2023-10-09 01:32 UTC, Skillz4Killz commented on packages/bot/src/handlers/channels/CHANNEL_PINS_UPDATE.ts
> +  if (bot.events.channelPinsUpdate === undefined) return
eww

2023-10-11 11:07 UTC, AwesomeStickz commented
Changed the if conditions, you can now review the PR again @Skillz4Killz

2023-10-15 04:27 UTC, Skillz4Killz approved these changes

2023-10-15 04:28 UTC, merged