feat: add after install script
discordeno/discordeno pull request #3161
Opened 2023-10-28 20:25 UTC by MatthewSH

This PR is primarily focused around husky and postinstall like scripts. The issue with Yarn is that it's not consistent with `postinstall` behavior and there's been many people with similar issues as we have with husky and Yarn monorepos as a whole. The best solution I found was to leverage a [Yarn Plugin](https://github.com/mhassan1/yarn-plugin-after-install/) that will run after after run of `yarn`/`yarn install`. After reviewing it and testing it, it suits our needs and works well.

I also added a `post-merge` hook that will look for any changes to yarn or package files to automatically run `yarn` to make sure contributors are always up to date and don't have to remember to run `yarn` after every clone.

Smaller changes:
- Fixed mode for `.husky` directory making it executable
- Updated yarn to latest 3.x release.

2023-10-28 21:20 UTC, H01001000 approved these changes

2023-10-28 21:21 UTC, H01001000 requested changes
Seen the docs site yarn lock not updated

2023-10-28 21:37 UTC, MatthewSH commented
@H01001000 fixed in https://github.com/discordeno/discordeno/pull/3161/commits/87dd0ee4b29bee882fe46b08057a55b14d313ca4

2023-10-28 21:39 UTC, H01001000 approved these changes

2023-10-29 14:37 UTC, Skillz4Killz approved these changes

2023-10-29 14:37 UTC, merged