fix(bot): Explicitly check for null or undefined
discordeno/discordeno pull request #3188
Opened 2023-11-26 17:49 UTC by Fleny113

In the transformer before there were the nullability checks that were using JS implicit conversion from anything to a boolean, this caused values like 0 to be converted to false and not put in the transformed object.

The pr also adds a `checkIfExists` as checking for null and/or undefined each time was overly verbose

---

Reported by @vxern on discord

2023-12-04 22:35 UTC, MatthewSH requested changes

2023-12-04 22:35 UTC, MatthewSH commented on packages/bot/src/transformers/channel.ts
> +  guildId?: BigString
this should be bigint

2023-12-11 19:13 UTC, MatthewSH approved these changes

2023-12-11 19:30 UTC, MatthewSH approved these changes

2023-12-22 01:49 UTC, H01001000 approved these changes

2023-12-22 01:50 UTC, H01001000 commented
@Fleny113 need you update branch

2023-12-22 05:10 UTC, merged