fix: docker app workflow
discordeno/discordeno pull request #3332
Opened 2023-12-20 23:43 UTC by MatthewSH

2023-12-20 23:44 UTC, H01001000 approved these changes

2023-12-20 23:46 UTC, Fleny113 approved these changes

2023-12-21 04:44 UTC, H01001000 requested changes
Keep the path filter for push, don’t want release every push

2023-12-21 05:38 UTC, H01001000 approved these changes

2023-12-21 06:09 UTC, Fleny113 approved these changes

2023-12-21 06:14 UTC, merged