chore(website): Cleanup docusaurus setup
discordeno/discordeno pull request #3355
Opened 2024-01-07 23:35 UTC by Fleny113

Fixes eslint (and lint-staged) setup for website
Migrates the TS setup from docusaurus v2 to v3
Updates dependencies
Adds Automatic JSX runtime (no more `import React from 'react'`)
Add typecheck workflow job as docusaurus does not use types for the build

2024-01-11 20:44 UTC, H01001000 approved these changes
it works it works

2024-01-11 20:47 UTC, H01001000 requested changes
@Fleny113 conflict

2024-01-12 01:46 UTC, H01001000 submitted a review, later dismissed

2024-02-09 19:33 UTC, MatthewSH approved these changes

2024-02-09 19:35 UTC, MatthewSH approved these changes

2024-02-09 20:34 UTC, H01001000 approved these changes

2024-02-09 20:39 UTC, merged