docs: Update contributing docs
discordeno/discordeno pull request #3386
Opened 2024-01-21 22:16 UTC by Fleny113

This pr cleans up some useless files and some fixes
- Remove tabnine from dev container
- Disable error matcher from watch task
- Link the website in the README.md
- Remove `packages/rest/src/REAME.md`

Currently there aren't the pull request guidelines as I didn't know what to add in there

closes #3171
closes #3172
closes #3174
closes #3176
closes #3179

2024-01-23 23:56 UTC, MatthewSH submitted a review, later dismissed

2024-02-09 20:44 UTC, MatthewSH submitted a review, later dismissed

2024-02-25 01:44 UTC, H01001000 requested changes

2024-02-25 01:44 UTC, H01001000 commented on website/docs/contributing.md
> +This will compile the TypeScript code into Javascript using SWC, it will not compile the type definitions (`.d.ts`) files.
this also removes the dir "clean build"

2024-02-25 11:31 UTC, H01001000 approved these changes

2024-03-08 04:40 UTC, Skillz4Killz approved these changes

2024-03-08 05:56 UTC, merged