fixed typo and updated bot review guild counts
discordeno/discordeno pull request #3641
Opened 2024-06-01 15:12 UTC by 8auu

updated all bot guild counts, fixed the appy logo no longer working and also fixed a typo in aiig review

2024-06-01 16:08 UTC, Fleny113 requested changes

2024-06-01 16:08 UTC, Fleny113 commented on website/src/components/home/reviews/index.tsx
> +        // 'https://cdn.discordapp.com/avatars/853327905357561948/a394518e742643f05cc201249d3ae75e.png',
```suggestion

```
Not sure why needs to be commented and can't be removed

2024-06-01 19:41 UTC, Fleny113 approved these changes

2024-06-03 07:04 UTC, lts20050703 approved these changes
LGTM!

2024-06-03 07:09 UTC, merged