fix(rest): check for snakelized names in `changeToDiscordFormat`
discordeno/discordeno pull request #3795
Opened 2024-07-23 10:30 UTC by Fleny113

Currently for `nameLocalizations`, `descriptionLocalizations` and some others, we have a special behavior. In the specific case of `nameLocalizations` and `descriptionLocalizations` that will skip the snakelization as that would break the format discord expects.

However, when the rest receives the objects already in the snake_case form (eg in a proxy) it will actually fail the check for `nameLocalizations` and `descriptionLocalizations` breaking the format that discord expects resulting in an error on the request

fixes #3666

2024-07-24 13:20 UTC, lts20050703 submitted a review, later dismissed
LGTM!

2024-07-30 18:48 UTC, AwesomeStickz requested changes

2024-07-30 18:48 UTC, AwesomeStickz commented on packages/rest/src/manager.ts
> +              case 'name_localizations':
```suggestion
              case 'description_localizations':
```

2024-07-30 18:49 UTC, AwesomeStickz commented
This or should we just do this?

```js
if (key.includes('_')) continue
```

2024-07-30 18:49 UTC, Fleny113 commented on packages/rest/src/manager.ts
> +              case 'name_localizations':
whoops

2024-07-30 18:50 UTC, Fleny113 commented
> This or should we just do this?
> 
> ```js
> if (key.includes('_')) continue
> ```

the issue is that this method will be called twice with a proxy, in the bot code and in the proxy, so this would prevent both from snakalize the key, wouldn't it?

2024-07-30 18:51 UTC, AwesomeStickz commented
> so this would prevent both from snakalize the key, wouldn't it?

Isn't the purpose to change camelized to snakelized version?

2024-07-31 04:38 UTC, merged