fix(discordeno)!: Fix some errors in `DiscordenoConfig`
discordeno/discordeno pull request #3824
Opened 2024-08-01 17:37 UTC by Fleny113

1. Fix typo in DesiredProp**rie**tiesBehavior
2. Remove the RecursivePartial<T> from `DiscordenoConfig.desiredProperies.properties` as it makes the object just harder to work with, as it is "lying" since the object should always be constructed with all the props

> [!WARNING]
> This is breaking since it is renaming a type

2024-08-01 20:07 UTC, AwesomeStickz requested changes

2024-08-01 20:07 UTC, AwesomeStickz commented on packages/discordeno/src/bin/config.ts
>        properties: createDesiredProprietiesObject(config.desiredProperties?.properties ?? {}),
```suggestion
      properties: createDesiredPropertiesObject(config.desiredProperties?.properties ?? {}),
```

2024-08-01 20:07 UTC, AwesomeStickz commented on packages/discordeno/src/bin/config.ts
> +    properties: TransformersDesiredProprieties
```suggestion
    properties: TransformersDesiredProperties
```

2024-08-01 20:08 UTC, AwesomeStickz commented
Could you actually go through entire codebase and replace all proprieties with properties while you’re at it?

2024-08-02 17:02 UTC, lts20050703 approved these changes
LGTM!

2024-08-03 04:45 UTC, AwesomeStickz approved these changes

2024-08-03 04:56 UTC, merged