build(website): Update website deps, remove 1s load time
discordeno/discordeno pull request #3858
Opened 2024-08-12 15:48 UTC by Fleny113

- Update website dependencies
- Remove 1s load time on /
- Remove default docusaurus assets
- Update README

2024-08-18 03:50 UTC, lts20050703 requested changes

2024-08-18 03:50 UTC, lts20050703 commented on website/src/pages/index.tsx
If we're removing the fake 1s load time, why not remove the loading screen altogether? Like remove the `const [loading, setLoading] = useState(true)`, the useEffect hook, and the `if (loading) return`

2024-08-18 05:22 UTC, Fleny113 commented on website/src/pages/index.tsx
Docusaurus will still pre-render that loading page, so when you load the page the loading is there until tge react bundle loads. Removing it creates a semi-unsyled hone page, reason for this is that while yes, the browser will wait for the CSS file before showing the HTML, since we use CSS in JS (styled-components) those styles are part of the JS bundle that did not yet load.

2024-08-21 16:30 UTC, AwesomeStickz approved these changes

2024-08-25 19:55 UTC, TriForMine approved these changes

2024-08-29 03:57 UTC, lts20050703 approved these changes

2024-08-29 09:22 UTC, merged