feat(embed-builder): add a addFields function
discordeno/discordeno pull request #4077
Opened 2024-12-30 16:17 UTC by mezotv

This implements a simple addFields function, similar to setFields, but instead of overwriting the previous fields it just adds them to the array. I also added a test for the addField function and fixed a typo in the tsdoc from earlier.

2024-12-30 16:19 UTC, mezotv commented
Ill try to fix the tests later moving this to a draft until that is figured out!

2024-12-30 16:25 UTC, itohatweb requested changes
Would it be possible to move the renaming to `EmbedsBuilder` to a separate PR? So we can avoid needing to bump a major version a bit longer.

2024-12-30 16:26 UTC, mezotv commented
> Would it be possible to move the renaming to `EmbedsBuilder` to a separate PR? So we can avoid needing to bump a major version a bit longer.

Its not actually a rename just changes the tsdoc. The class was always named like this. But yea if needed I can make a seperate pr for it!

2024-12-30 16:29 UTC, Fleny113 commented on packages/utils/src/builders/embeds.ts
> +    this.#currentEmbed.fields.push(fields)
```suggestion
    this.#currentEmbed.fields.push(...fields)
```

2024-12-30 18:04 UTC, Fleny113 submitted a review, later dismissed

2024-12-30 18:04 UTC, Fleny113 commented on packages/utils/src/builders/embeds.ts
> +   * @param {DiscordEmbedField[]} fields
```suggestion
   * @param {DiscordEmbedField[]} fields - The fields to add
```

2024-12-30 18:05 UTC, Fleny113 submitted a review, later dismissed

2024-12-31 00:06 UTC, Skillz4Killz approved these changes

2024-12-31 00:06 UTC, merged