feat(types,bot): UI
discordeno/discordeno pull request #4080
Opened 2024-12-31 16:38 UTC by Fleny113

2025-02-28 20:24 UTC, lts20050703 requested changes
I see a lot of TBD comments, is the official docs for Components V2 out yet?

2025-02-28 20:24 UTC, lts20050703 commented on packages/types/src/discordeno.ts
>  export interface CreateGuildChannel {
```suggestion
/** https://discord.com/developers/docs/resources/guild#create-guild-channel */

export interface CreateGuildChannel {
```

2025-03-01 04:44 UTC, AwesomeStickz commented
> I see a lot of TBD comments, is the official docs for Components V2 out yet?

Yeah it's not mergeable yet, we're waiting on Discord to add it to docs so we can add the comments to dd

2025-04-23 21:52 UTC, lts20050703 commented on packages/bot/src/transformers/component.ts
> +    case MessageComponentTypes.File:
Type of `component.file` is [unfurled media item](https://discord.com/developers/docs/components/reference#unfurled-media-item-structure), which has snake case and null, so do we need to transform it?

2025-04-23 21:52 UTC, lts20050703 commented on packages/bot/src/transformers/component.ts
> +    case MessageComponentTypes.MediaGallery:
Type of `component.items[number].media` is [unfurled media item](https://discord.com/developers/docs/components/reference#unfurled-media-item-structure), which has snake case and null, so do we need to transform it?

2025-04-23 21:52 UTC, lts20050703 commented on packages/bot/src/transformers/component.ts
> +    case MessageComponentTypes.Thumbnail:
Type of `component.media` is [unfurled media item](https://discord.com/developers/docs/components/reference#unfurled-media-item-structure), which has snake case and null, so do we need to transform it?

2025-04-23 21:52 UTC, lts20050703 commented on packages/bot/src/transformers/types.ts
> +  file?: DiscordUnfurledMediaItem
Should we transform from snake_case to camelCase?

2025-04-23 21:52 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +  Section = 9,
```suggestion
  Section,
```

2025-04-23 21:52 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +  components: Exclude<DiscordMessageComponent, DiscordActionRow>[]
```suggestion
  components:
    | [Exclude<MessageComponent, ActionRow>]
    | [ButtonComponent, ButtonComponent]
    | [ButtonComponent, ButtonComponent, ButtonComponent]
    | [ButtonComponent, ButtonComponent, ButtonComponent, ButtonComponent]
    | [ButtonComponent, ButtonComponent, ButtonComponent, ButtonComponent, ButtonComponent]
```

2025-04-23 21:52 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +export interface DiscordInputTextComponent extends DiscordBaseComponent {
```suggestion
export interface DiscordTextInputComponent extends DiscordBaseComponent {
```
This would be a type breaking change, but it took me a minute to search the codebase not knowing it's InputText, like why did you change the name Discord

2025-04-23 21:52 UTC, lts20050703 commented on packages/types/src/discordeno.ts
> +  media: DiscordUnfurledMediaItem
Type of `component.media` is [unfurled media item](https://discord.com/developers/docs/components/reference#unfurled-media-item-structure), which has snake case and null, so do we need to transform it?

2025-04-23 21:52 UTC, lts20050703 commented on packages/types/src/discordeno.ts
> +  file: DiscordUnfurledMediaItem
Type of `component.file` is [unfurled media item](https://discord.com/developers/docs/components/reference#unfurled-media-item-structure), which has snake case and null, so do we need to transform it?

2025-04-23 21:52 UTC, lts20050703 commented on packages/types/src/discordeno.ts
> +  components: Array<ActionRow | TextDisplayComponent | SectionComponent | MediaGalleryComponent | SeparatorComponent | FileComponent>
Do we want to hard code max 10 elements in an array like ActionRow.components hard coding max 5 buttons component or a single "not buttons" component lol

2025-04-23 21:53 UTC, lts20050703 commented
I think that we should have desiredProperties for components as well, for full coverage, but that probably should be in another PR.

2025-04-23 21:59 UTC, Fleny113 commented on packages/types/src/discordeno.ts
> +  components: Array<ActionRow | TextDisplayComponent | SectionComponent | MediaGalleryComponent | SeparatorComponent | FileComponent>
all the different types in the union would be quite a lot, no?

2025-04-24 00:16 UTC, lts20050703 commented on packages/types/src/discordeno.ts
> +  components: Array<ActionRow | TextDisplayComponent | SectionComponent | MediaGalleryComponent | SeparatorComponent | FileComponent>
Yeah... it's up to you tbh, since maybe users should read the docs, or at the very least, hover over the props and see the first 3 words are literally "Up to 10"

2025-04-24 17:58 UTC, Fleny113 commented on packages/types/src/discordeno.ts
> +  components: Array<ActionRow | TextDisplayComponent | SectionComponent | MediaGalleryComponent | SeparatorComponent | FileComponent>
Also, I don't like that much that we do the whole `[ButtonComponent] | [ButtonComponent, ButtonComponent] | [...] | ...`.

Yeah, sure it makes TS give you an error when you are manually doing the array, however the instant you try to work with that as an array and not a ""tuple"" (so `.shift()`, `.push()` etc) it falls apart and you need a cast to `as CointainerComponent['components']` (or the `ActionRow` if you are using that, but the idea is the same) since TS will have to widen the type from `[ButtonComponent]` to `ButtonComponent[]`

2025-04-24 18:04 UTC, Fleny113 commented on packages/types/src/discordeno.ts
> +  components: Array<ActionRow | TextDisplayComponent | SectionComponent | MediaGalleryComponent | SeparatorComponent | FileComponent>
https://tsplay.dev/mxVr7w shows the issue a bit more clearly

To correct myself, it is not that TS has to widen the type, it doesn't care, however when you create said tuple you get an error since it is not what you are saying it is, and if you try to create the tuple by using an array you get an error because an array MAY have less or more elements that the tuple you specified

2025-04-24 18:05 UTC, Fleny113 commented on packages/types/src/discord/components.ts
> +  components: Exclude<DiscordMessageComponent, DiscordActionRow>[]
See https://github.com/discordeno/discordeno/pull/4080#discussion_r2058970495, as it is about this very thing

2025-04-24 22:13 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +  components: Exclude<DiscordMessageComponent, DiscordActionRow>[]
Hmm I see, it's quite annoying
Maybe let's just make it a JSDoc comment remarks instead

2025-04-24 22:14 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +  // TODO: Potenzially this could be changed to (DiscordButtonComponent | DiscordSelectMenuComponent)[]
Is it better to keep it as is or change it to `DiscordButtonComponent | DiscordSelectMenuComponent`?

2025-04-24 22:35 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +  components: Exclude<DiscordMessageComponent, DiscordActionRow>[]
```suggestion
  /**
   * The components in this row
   * 
   * @remarks
   * Up to 5 button components or a single select component
   */
  components: (DiscordButtonComponent | DiscordSelectMenuComponent)[]
```

2025-04-24 22:35 UTC, lts20050703 commented on packages/types/src/discordeno.ts
> +  components: Array<ActionRow | TextDisplayComponent | SectionComponent | MediaGalleryComponent | SeparatorComponent | FileComponent>
Yeah I can see what you mean, it's quite annoying

2025-04-24 22:35 UTC, lts20050703 commented on packages/bot/src/transformers/reverse/component.ts
> +    case MessageComponentTypes.Thumbnail:
This needs to be transformed as well

2025-04-24 22:35 UTC, lts20050703 commented on packages/bot/src/transformers/component.ts
> +      break
Actually/Technically, Thumbnail, MediaGallery, and File doesn't need to be transformed back to snake case. The reason is simple, the docs say Discord ignore the snake case fields anyways, so there's no point in transforming those property back to snake case before sending to Discord just for Discord to ignore them.

> This field is ignored and provided by the API as part of the response

https://discord.com/developers/docs/components/reference#unfurled-media-item-structure
(You might need to scroll down or click Unfurled Media Item Structure twice, Discord really need to fix this lol)

2025-04-25 01:31 UTC, Fleny113 commented on packages/bot/src/transformers/component.ts
> +      break
I'd say that it doesn't matter and we should transform it anyway in case someone has a use case for it

Also i feel like it is easier to just do it rather than explain in a comment why would it be ignored

(about the docs link, yeah i have noticied it too, after the page is loaded if you go to the address bar and press enter it does scroll, for me at least, bc i think #.. is a browser thing but the docs aren't actually a SSR / SSG page so the browser at page load doesn't know where to scroll to. As a note the SSR / SSG thing is just a guess on why it doesn't work, i haven't checked)

2025-04-25 23:06 UTC, lts20050703 requested changes
merge conflicts 😅

2025-04-25 23:06 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +  components: (DiscordButtonComponent | DiscordSelectMenuComponent | DiscordTextInputComponent)[]
Hi @Fleny113 , did you test this or something? The docs only mention up to 5 button or a single select menu component, i dont see any mention of text input component.

2025-04-25 23:09 UTC, lts20050703 commented on packages/types/src/discord/components.ts
> +  components: (DiscordButtonComponent | DiscordSelectMenuComponent | DiscordTextInputComponent)[]
My bad, i made the same mistake I told you 😅
Discord really need to fix the docs lol

2025-04-26 06:31 UTC, lts20050703 approved these changes
LGTM!

2025-04-26 06:35 UTC, merged