Add functions to channel structure
discordeno/discordeno pull request #424
Opened 2021-01-20 15:58 UTC by MilSci

**Please describe the changes this PR makes and why it should be merged:**
- get VoiceStates() function was added to get the voice states of a channel
- get connectedMembers() function was added to get the connected voice members of a channel
- disconnectMember(memberID) function was added to remove a member from the voice channel

**Status**

- [x] Code changes have been tested against the Discord API, or there are no
  code changes

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed,
    parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation,
  README, etc.

2021-01-20 16:02 UTC, ayntee commented on src/api/structures/channel.ts
> +  disconnectMember(memberID) {
```suggestion
  disconnectMember() {
```

2021-01-20 16:04 UTC, ayntee commented on src/api/structures/channel.ts
> +    kickFromVoiceChannel(guildID, memberID);
```suggestion
    kickFromVoiceChannel(this.guildID, memberID);
```

2021-01-20 16:05 UTC, ayntee commented on src/api/structures/channel.ts
> +    return voiceStates;
```suggestion

    return voiceStates;
```

2021-01-20 16:05 UTC, itohatweb requested changes

2021-01-20 16:05 UTC, itohatweb commented on src/api/structures/channel.ts
> +    kickFromVoiceChannel(guildID, memberID);
```suggestion
    kickFromVoiceChannel(this.guildID!, memberID);
```

2021-01-20 16:06 UTC, ayntee commented on src/api/structures/channel.ts
> +    );
```suggestion
    const guild = cache.guilds.get(this.guildID);
    if (!guild) return;
    return guild.voiceStates.filter(voiceState => voiceState.channelID === this.id);
```

2021-01-20 16:08 UTC, ayntee commented on src/api/structures/channel.ts
> +    return voiceStates;
```suggestion
```

2021-01-20 16:11 UTC, MilSci commented on src/api/structures/channel.ts
> +    if (!guild) return;
if(!guild) return undefined;

2021-01-20 16:16 UTC, itohatweb commented on src/api/structures/channel.ts
> +    return memberCollection;
```suggestion
  get connectedMembers() {
    return new Collection(
      this.voiceStates?.map(
        (vs) => [vs.member?.user.id!, cache.members.get(vs.member?.user.id!)]
      ) || [],
    );
  },
```

2021-01-20 16:20 UTC, itohatweb requested changes

2021-01-20 16:20 UTC, itohatweb commented on src/api/structures/channel.ts
> +    if (!guild) return;
```suggestion
    const guild = cache.guilds.get(this.guildID!);
    if (!guild) return undefined;
```

2021-01-20 16:20 UTC, itohatweb commented on src/api/structures/channel.ts
> +  },
```suggestion
```

2021-01-20 16:20 UTC, itohatweb commented on src/api/structures/channel.ts
> +    kickFromVoiceChannel(this.guildID, memberID);
```suggestion
    kickFromVoiceChannel(this.guildID!, memberID);
```

2021-01-20 16:36 UTC, itohatweb commented on src/api/structures/channel.ts
> +  disconnectMember(memberID) {
Please rename to `kickFromVoice` for consistency.

2021-01-21 21:39 UTC, Skillz4Killz requested changes

2021-01-21 21:39 UTC, Skillz4Killz commented on src/api/structures/channel.ts
> +    return guild.voiceStates.filter(voiceState => voiceState.channelID === this.id);
Always a space after `return` add empty line plz

2021-01-21 21:39 UTC, Skillz4Killz commented on src/api/structures/channel.ts
> +    if (!guild) return undefined;
```suggestion
    if (!guild) return new Collection();
```

2021-01-21 21:39 UTC, Skillz4Killz commented on src/api/structures/channel.ts
> +    kickFromVoiceChannel(this.guildID!, memberID);
```suggestion
    return kickFromVoiceChannel(this.guildID!, memberID);
```

2021-01-21 21:39 UTC, Skillz4Killz commented on src/api/structures/channel.ts
> +
remove extra line

2021-01-21 21:39 UTC, Skillz4Killz commented on src/api/structures/channel.ts
> +  kickFromVoice(memberID: string): void;
```suggestion
  kickFromVoice(memberID: string): ReturnType<typeof kickFromVoiceChannel >;
```

2021-01-21 21:39 UTC, Skillz4Killz commented on src/api/structures/guild.ts
> +  kickFromVoice(memberID: string): void;
```suggestion
  kickFromVoice(memberID: string): ReturnType<typeof kickFromVoiceChannel>;
```

2021-01-21 21:39 UTC, Skillz4Killz commented on src/api/structures/member.ts
> +  kickFromVoice(guildID: string): void;
```suggestion
  kickFromVoice(guildID: string): ReturnType<typeof kickFromVoiceChannel>;
```

2021-01-21 21:47 UTC, Skillz4Killz commented on src/api/structures/channel.ts
> +    return new Collection(
This thing might be better as ```ts
return this.voiceStates.map((vs, key) => [key, cache.members.get(key)])
```

2021-01-26 14:28 UTC, Skillz4Killz requested changes
Still pending changes from previous reviews

2021-02-06 14:26 UTC, closed without merging