fix(ws/shard): update status update payload
discordeno/discordeno pull request #559
Opened 2021-03-01 15:14 UTC by ayntee

Closes #526

2021-03-01 15:27 UTC, itohatweb requested changes

2021-03-01 15:27 UTC, itohatweb commented on src/types/discord.ts
> +  activities: Activity[] | null;
```suggestion
  activities: Pick<ActivityPayload, "name" | "type" | "url">[] | null;
```
Bots are only allowed to use `name`, `type` and `url`. I am not sure if bots are allowed to have multiple activities.

2021-03-01 15:37 UTC, ayntee commented on src/types/discord.ts
> +import { ActivityPayload } from "./mod";
```suggestion
import { ActivityPayload } from "./mod.ts";
```

2021-03-08 15:36 UTC, Skillz4Killz approved these changes

2021-03-08 15:36 UTC, Skillz4Killz commented on src/util/utils.ts
> +  data: GatewayStatusUpdatePayload,
why force a dev to pass in since/afk if they never get used?

2021-03-08 15:37 UTC, Skillz4Killz approved these changes

2021-03-08 15:38 UTC, itohatweb approved these changes

2021-03-08 15:41 UTC, merged