feat: implement stage instances
discordeno/discordeno pull request #924
Opened 2021-05-11 11:58 UTC by rigormorrtiss

- feat: implement stage instances
- feat: implement stage instances

2021-05-11 12:04 UTC, rigormorrtiss commented on src/helpers/misc/delete_stage_instance.ts
> +  return await rest.runMethod<{}>(
If the body is not dispatched from the server, the runMethod() returns an empty JSON-parsed object instead.
The type could be changed to `Record<...>` instead, however, it was obscure and ambiguous, hence, `{}`.

2021-05-11 19:45 UTC, itohatweb requested changes
Please move the stage instance helpers to the channel folder.

2021-05-11 19:45 UTC, itohatweb commented on src/helpers/misc/update_stage_instance.ts
> +export async function updateStageInstance(channelId: bigint, topic: string) {
Add proper perm checks

2021-05-11 19:48 UTC, itohatweb commented on src/helpers/mod.ts
> +  deleteStageInstance,
move this to channels

2021-05-11 19:49 UTC, itohatweb commented on src/helpers/misc/create_stage_instance.ts
> +export async function createStageInstance(channelId: string, topic: string) {
also check if the target channel is a stage channel

2021-05-12 10:35 UTC, itohatweb requested changes

2021-05-12 10:35 UTC, itohatweb commented on src/helpers/channels/create_stage_instance.ts
> +import { StageInstance } from "../../types/channels/stage_instance.ts";
Use import type to import interfaces
```suggestion
import type { StageInstance } from "../../types/channels/stage_instance.ts";
```

2021-05-12 10:35 UTC, itohatweb commented on src/helpers/channels/get_stage_instance.ts
> +import { StageInstance } from "../../types/channels/stage_instance.ts";
Use import type to import interfaces
```suggestion
import type { StageInstance } from "../../types/channels/stage_instance.ts";
```

2021-05-12 10:35 UTC, itohatweb commented on src/helpers/channels/update_stage_instance.ts
> +import { StageInstance } from "../../types/channels/stage_instance.ts";
Use import type to import interfaces
```suggestion
import type { StageInstance } from "../../types/channels/stage_instance.ts";
```

2021-05-12 10:35 UTC, itohatweb commented on src/helpers/channels/create_stage_instance.ts
> +  if (!channel) throw new Error(Errors.CHANNEL_NOT_FOUND);
Do not throw an error if the channel is not cached instead use `if (channel) // do checks`

2021-05-12 10:35 UTC, itohatweb commented on src/helpers/channels/delete_stage_instance.ts
> +  if (!channel) throw new Error(Errors.CHANNEL_NOT_FOUND);
Do not throw an error if the channel is not cached instead use `if (channel) // do checks`

2021-05-12 10:35 UTC, itohatweb commented on src/helpers/channels/get_stage_instance.ts
> +  if (!channel) throw new Error(Errors.CHANNEL_NOT_FOUND);
Do not throw an error if the channel is not cached instead use `if (channel) // do checks`

2021-05-12 10:35 UTC, itohatweb commented on src/helpers/channels/update_stage_instance.ts
> +  if (!channel) throw new Error(Errors.CHANNEL_NOT_FOUND);
Do not throw an error if the channel is not cached instead use `if (channel) // do checks`

2021-05-12 10:48 UTC, itohatweb approved these changes

2021-05-12 12:24 UTC, itohatweb commented
Just talked to skillz, can you add unit tests for these functions?

2021-05-12 13:57 UTC, merged