feat: add stage discovery fields
discordeno/discordeno pull request #957
Opened 2021-05-21 07:21 UTC by rigormorrtiss

Re﻿ference: https://github.com/discord/discord-api-docs/pull/2971

2021-05-21 19:38 UTC, itohatweb requested changes

2021-05-21 19:38 UTC, itohatweb commented on src/types/channels/privacy_level.ts
> +  Public,
enums start at 0 but discord at 1
```suggestion
  Public = 1,
```

2021-05-21 19:44 UTC, itohatweb commented
Please resolve the conflicts

2021-05-22 03:18 UTC, Skillz4Killz commented
Need unit tests

2021-05-22 07:19 UTC, itohatweb commented
Did you test the changes localy and can you confirm that they work?

2021-05-22 07:38 UTC, rigormorrtiss commented
> Did you test the changes localy and can you confirm that they work?

Yes

2021-05-22 07:40 UTC, itohatweb commented
@Skillz4Killz I will merge it now since it is impossible to do tests rn because discord does not allow bots to create conmunity guilds.

2021-05-22 07:40 UTC, itohatweb approved these changes

2021-05-22 07:41 UTC, merged