feat(types/guilds): add nsfw_level field to Guild
discordeno/discordeno pull request #958
Opened 2021-05-21 08:03 UTC by rigormorrtiss

Reference: https://github.com/discord/discord-api-docs/pull/2976

2021-05-21 14:55 UTC, Skillz4Killz commented on src/types/guilds/guild_nsfw_level.ts
> +export enum GuildNSFWLevel {
I would make this GuildNsfwLevel to just fit the camelCase theme

2021-05-21 14:55 UTC, Skillz4Killz commented on .gitignore
> +.sublime-project
Remove everything in this file besides debug.ts

2021-05-22 07:41 UTC, rigormorrtiss commented on src/types/guilds/guild.ts
> +  nsfwLevel: GuildNSFWLevel;
```suggestion
  /** Guild NSFW level */
  nsfwLevel: GuildNsfwLevel;
```

2021-05-22 07:42 UTC, rigormorrtiss commented on src/types/guilds/guild_nsfw_level.ts
> +export enum GuildNSFWLevel {
```suggestion
export enum GuildNsfwLevel {
```

2021-05-22 07:46 UTC, itohatweb requested changes

2021-05-22 07:46 UTC, itohatweb commented on src/types/guilds/guild.ts
> +import { GuildNSFWLevel } from "./guild_nsfw_level.ts";
```suggestion
import { GuildNsfwLevel } from "./guild_nsfw_level.ts";
```

2021-05-22 07:50 UTC, itohatweb approved these changes

2021-05-22 07:50 UTC, merged